language: node_js
node_js:
  - "node"

services:
  - postgresql

install:
  - cd backend
  - npm install
  - cd ../frontend
  - npm install
  - cd ..

before_script:
  - psql -c 'create database "distributed-systems-test"' -U postgres

script:
  - cd backend
  - npm test
  - cd ..

branches:
  only:
    - master